### ISSUE TITLE
Slowdown while creating very deep trees (1000+ depth)

### ISSUE THREAD

**Issue by RomStriker** [kayjan/bigtree#185]
Hi,

I am trying to convert very large networkx directed graphs (trees) with depth larger than 1000 to bigtree objects. As the depth of the tree increases the processes slowdown, maybe due to recursion overhead. Is there a way to speed this up?

**Comment by kayjan** [comment]
Hello, thanks for bringing this up. May I know if you are constructing tree using what method(s)? I suspect it is the tree checks that are done when creating tree since it will check for
- Illegal loops (i.e., cyclical nodes) which involves checking the whole ancestry of a node, this affects trees that are very deep
- Illegal children (i.e., siblings with same name), this affects trees that are very wide

Will it be useful if I added a feature to check off these checks? Only to be used if you are very certain your tree does not violate the checks

**Comment by RomStriker** [comment]
I am using `nx.bfs_layers(tree, root_node_id)` to traverse the networkx tree level by level, and add it to a bigtree by just initializing a new node Node(name, position=pos, parent=parent_node) for every node. 
I am sure that the the graph is a tree, and I am manually keeping check of names, so it would be great if I could turn those checks off.

**Comment by kayjan** [comment]
Hello, thanks for your patience! I have fixed this in `v0.16.2`, do upgrade bigtree by performing `pip install --upgrade bigtree`.

There will be some code changes required on your side to turn off these checks. Do follow the instructions [here](https://bigtree.readthedocs.io/en/latest/others/remove_checks/)!

**Comment by RomStriker** [comment]
Great, thanks. It is faster than before but it still slows down as the tree get deeper more noticible after depth 600+.

**Comment by kayjan** [comment]
Hmm, not sure if it a problem caused by depth now. What’s the size of your tree (how many nodes, the width and depth)?
