### ISSUE TITLE
`list_to_tree` fails to construct a tree when files have no parent (i.e in root)

### ISSUE THREAD

**Issue by Ravencentric** [kayjan/bigtree#232]
**Describe the issue**
`list_to_tree` fails to construct a tree when files have no parent

**Environment**
Describe your environment.
 - Platform: Windows 11
 - Python version: 3.11.8
 - `bigtree`  version: 0.17.2

**To Reproduce**
Steps or code to reproduce the behaviour:
Run this code:
Example A:
```py
from bigtree.tree.construct import list_to_tree

# foo.txt and bar.txt are in root
paths = ["foo.txt", "bar.txt"]

tree = list_to_tree(paths)
tree.show()
```
Example B:
```py
from bigtree.tree.construct import list_to_tree

# foo.txt, bar.txt, and recipe are in root
paths = ["foo.txt", "bar.txt", "recipe/spam.txt", "recipe/eggs.txt"]

tree = list_to_tree(paths)
tree.show()
```

**Expected behaviour**
Possibly show the root like so?
Example A:
```
.
├── foo.txt
└── bar.txt
```
Example B:
```
.
├── recipe
│   ├── eggs.txt
│   └── spam.txt
├── foo.txt
└── bar.txt
```

**Screenshots**
N/A

**Additional context**
N/A

**Comment by kayjan** [comment]
This is intended to be the case as `paths = ["foo.txt", "bar.txt"]` could be misleading, and even more ambiguous/misleading with added `recipe` in your Example B.

What you can do is to append a `"./"` infront of every path string in the list so it is clearer that your desired root node is `.`. For example, using `paths = ["./foo.txt", "./bar.txt"]` would get the expected behaviour you want.
